### PR TITLE
feat: use default daemon addrs

### PR DESCRIPTION
**Pull request by dryajov**

### CODE REVIEW

**Comment by hacdias** [comment]
@dryajov is this working already? 😄

**Comment by dryajov** [comment]
Yup. Can you do a CR 😉?

**Comment by hacdias** [comment]
Hoping CR means something like "Closing Review", I did it 😆

**Comment by dryajov** [comment]
Oh `CR` - Code Review, AFAIK 😄

**Comment by hacdias** [comment]
Thanks eheh. When you merge this and release a new version, could you ping me please?

**Comment by dryajov** [comment]
@JonKrone it's addressing this issue - https://github.com/ipfs-shipyard/ipfs-desktop/issues/617

**Comment by diasdavid** [comment]
@dryajov CI is not yet green. Can you get that done before more reviews?

**Comment by dryajov** [comment]
CI is mostly failing because this adds the ability to use the daemon's default ports, which conflicts on jenkins since tests are not isolated. We'll probably have to skip this tests on jenkins for now.

screen shot 2018-03-22 at 6 42 26 pm

**Comment by dryajov** [comment]
Skiping the default addrs test fixes jenkins. But circle ci is really broken for some reason, there are a bunch of timeouts everywhere. I'm not sure if its related to the recent outage or if its something else.

**Comment by dryajov** [comment]
@diasdavid circleci is having some serious issues, but I don't think it's related to these changes. After I disabled the default addrs tests, jenkins and travis are now both green, however circle keeps failing on random timeouts. I'm not sure what's the best way of verifying that circle is the one with the issues besides closing this PR and opening a new one? 

@VictorBjelkholm whats the versions of node that circle is on, I can't seem to find it anywhere in the logs, that could be the reason it's failing since #223 as been brought up.

**Comment by VictorBjelkholm** [comment]
> whats the versions of node that circle is on, I can't seem to find it anywhere in the logs

Eeeh, hm. You can see under the `machine` logs:
image

**Pull request merged**
