### PR TITLE
feat: add --migrate

### PR DESCRIPTION
**Pull request by bluelovers**

### CODE REVIEW

**Review by achingbrain — CHANGES_REQUESTED** [review]
Can you add a test for this please.

As the configuration matrix gets more complicated we'll need some way of verifying functionality like this.

**Comment by bluelovers** [comment]
how can i add test when current not exists any test for options

it is not a shared function

**Comment by achingbrain** [comment]
I would refactor the creation of the `args` array into a method on the `Daemon` class called `_buildArgs(opts)`.

Invoke that method in the test an assert that the correct arg is added for the given option.

**Comment by bluelovers** [comment]
so can u merge this, any maybe one day this repo will splitting code for make it reuse/test able

**Comment by achingbrain** [comment]
No, I think new code needs tests, otherwise we cannot guarantee there will be no regressions in future.  Please add a test, I've outlined how to do it.

**Comment by bluelovers** [comment]
@achingbrain ok, refactor done

**Comment by achingbrain** [comment]
CI is failing on this PR, could you please take a look?

**Comment by jacobheun** [comment]
@bluelovers can you take a look at the CI failures?

**Comment by achingbrain** [comment]
Will be landed in #542 as this PR has been abandoned.

**Comment by bluelovers** [comment]
@achingbrain do not ask change code out of my pr want to do at next time, thx

**Pull request closed without merging**
