### PR TITLE
fix: try with a different port

### PR DESCRIPTION
**Pull request by diasdavid**

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
:-1: not a proper fix as this might break in the future too. We cannot make assumptions about free ports (but I bet you already knew this). As mentioned elsewhere, I'm working on fixing this right now.

**Comment by diasdavid** [comment]
@VictorBjelkholm I'm testing you hypothesis from https://github.com/ipfs/js-ipfsd-ctl/issues/206#issuecomment-367635620

I claim that it isn't the port but rather the server that is not being closed properly.

**Comment by diasdavid** [comment]
Alright, seems that indeed Mac OS uses port 9999 for something, so the server is being closed properly.

image

👌🏽

**Comment by VictorBjelkholm** [comment]
> Making the port random generated would just hide the problem for now, but it would create issues for users

The fix I'm working on doesn't involve ipfsd-ctl at all, just how ipfs/js-ipfs is using it.

**Comment by dryajov** [comment]
I say we change the port to something else - the one here seems reasonable, `9999` seems too common and super easy to clash with. @diasdavid lets get this merged?

**Comment by VictorBjelkholm** [comment]
Silly but `4737` would mean `IPFS` on a T9 keyboard (and US phonenumbers somehow?). Would be a good port and easy to remember if you used to send sms's a couple of years ago :tada:

**Comment by diasdavid** [comment]
#211

**Comment by diasdavid** [comment]
@VictorBjelkholm that one would be good for the ipfs daemon default listening port :)

**Pull request closed without merging**
